/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sprint (https://sketchfab.com/Sprintpt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-car-6e624fba16914888bd435fb697f4a2b9
Title: Low poly car
*/

import * as THREE from 'three'
import React, { } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_31: THREE.Mesh
    Object_33: THREE.Mesh
    Object_35: THREE.Mesh
    Object_37: THREE.Mesh
    Object_39: THREE.Mesh
  }
  materials: {
    material_0: THREE.MeshStandardMaterial
  }
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="bone_18">
                <group name="68c68d8a-d87d-8700-3deb-0b8b3576c1d9_0">
                  <mesh
                    name="Object_5"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_5.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="600d4303-d287-c297-199f-8a9c4f00beba_1">
                  <mesh
                    name="Object_7"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_7.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group
                  name="5c189f44-af4e-23d4-d839-efdec4f4ce86_2"
                  position={[0.8, 12.067, -10.658]}
                  rotation={[-0.96, 0, 0]}>
                  <mesh
                    name="Object_9"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_9.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group
                  name="89d9b6e7-c507-7ba1-fb02-1599aabf75d2_3"
                  position={[1.6, 41.719, 10.542]}
                  rotation={[Math.PI / 4, 0, 0]}>
                  <mesh
                    name="Object_11"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_11.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="ebcb60d4-a73c-d7c4-15a3-3c832fb8b693_4">
                  <mesh
                    name="Object_13"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_13.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="d6752107-08fc-797c-870c-86883fd99196_5">
                  <mesh
                    name="Object_15"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_15.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="4515c510-d2b1-eecb-bb8e-d894734f9c84_6">
                  <mesh
                    name="Object_17"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_17.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="9a8307dc-66b5-a1d2-1926-5061f9a0f178_7">
                  <mesh
                    name="Object_19"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_19.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="668df5d8-8f9e-e1a2-4545-29b151b4f18b_8">
                  <mesh
                    name="Object_21"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_21.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="a21a449d-0d1c-6826-bded-1d768a55bec7_9">
                  <mesh
                    name="Object_23"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_23.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="b6f5fbf3-8c38-4ae5-cf56-109cd6ead49a_10">
                  <mesh
                    name="Object_25"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_25.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="23a6cfb0-b6a0-5ebd-0430-e2fa4aa005b7_11">
                  <mesh
                    name="Object_27"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_27.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="942d8e9b-e8d1-0ff1-6244-39a2c83b3f06_12">
                  <mesh
                    name="Object_29"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_29.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group
                  name="246304f4-34a3-a4fb-a7fd-cd0da50a80de_13"
                  position={[1, 8, 16]}
                  rotation={[-0.087, 0, 0]}>
                  <mesh
                    name="Object_31"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_31.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group
                  name="b2cb1ec6-c334-c987-c79a-721444f56ab3_14"
                  position={[1, 8, 16]}
                  rotation={[0.14, 0, 0]}>
                  <mesh
                    name="Object_33"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_33.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="3aa2c063-1ee8-5d33-aa9e-41baef97bb8e_15">
                  <mesh
                    name="Object_35"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_35.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group name="2476bf9b-a751-54d0-b775-522c771ce12b_16">
                  <mesh
                    name="Object_37"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_37.geometry}
                    material={materials.material_0}
                  />
                </group>
                <group
                  name="c5cd5247-477d-9608-e852-c83a0f7ca581_17"
                  position={[0, 13.583, 34.449]}
                  rotation={[-Math.PI / 6, 0, 0]}>
                  <mesh
                    name="Object_39"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_39.geometry}
                    material={materials.material_0}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
