/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Gabriel Solon (https://sketchfab.com/gabriel_solon)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/psx-saviola-s21-900a5f093cee47f1bfd0df0fd3b3a721
Title: PSX Saviola S21
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.SkinnedMesh
    Object_12: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    MAT_marco: THREE.MeshStandardMaterial
    MAT_saviola: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Saviola flight' | 'savolas21_armature|Saviola flight'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/scene.gltf') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="sketchfab_saviolafbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="marco"
                  position={[0.01, 20.1, -29.48]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group
                  name="Saviola"
                  position={[0, -15.52, 55.66]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
                <group name="savolas21_armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_7">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_10"
                      geometry={nodes.Object_10.geometry}
                      material={materials.MAT_marco}
                      skeleton={nodes.Object_10.skeleton}
                    />
                    <skinnedMesh
                      name="Object_12"
                      geometry={nodes.Object_12.geometry}
                      material={materials.MAT_saviola}
                      skeleton={nodes.Object_12.skeleton}
                    />
                    <group
                      name="Object_9"
                      position={[0.01, 20.1, -29.48]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                    <group
                      name="Object_11"
                      position={[0, -15.52, 55.66]}
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
